# Generated by Django 4.1.3 on 2022-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult_tic_tac_toe', '0002_alter_game_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
