# Generated by Django 4.1.5 on 2023-01-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult_tic_tac_toe', '0003_game_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
